package com.esjr.bluejay;

public enum TokenType {
    LEFT_PAREN, RIGHT_PAREN, LEFT_SQUARE,
    RIGHT_SQUARE, LEFT_BRACE, RIGHT_BRACE,
    COMMA, DOT, MINUS, NEWLINE, PERCENT,
    PLUS, SLASH, STAR,

    BANG, BANG_EQUAL,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,
    STAR_STAR,

    ID, STR, NUM,

    AND, CLASS, ELSE, FALSE, FUNC, FOR, IF, NOT,
    NULL, OR, PRINT, RETURN, SUPER, THIS, TRUE,
    VAR, WHILE, XOR,

    EOS, // End Of Statement

    EOF
}