package com.esjr.bluejay;

public enum TokenType {
    COLON, LEFT_PAREN, RIGHT_PAREN, LEFT_SQUARE,
    RIGHT_SQUARE, LEFT_BRACE, RIGHT_BRACE,
    COMMA, DOT, MINUS, NEWLINE, PERCENT,
    PLUS, SLASH, STAR,

    PLUS_EQUAL, MINUS_EQUAL, STAR_EQUAL, SLASH_EQUAL,
    STAR_STAR_EQUAL, PERCENT_EQUAL,

    BANG, BANG_EQUAL,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,
    STAR_STAR,
    PLUS_PLUS, MINUS_MINUS,

    ID, STR, NUM,

    AND, BREAK, CLASS, ELSE, FALSE, FUNC, FOR, FOREACH, FROM, IF, IMPORT, IN, NOT,
    NULL, OR, REPEAT, RETURN, SUPER, THIS, TRUE,
    VAR, WHILE, XOR,

    EOS, // End Of Statement

    EOF
}